version: '2' 
services:
  namenode:
    image: docker.arvancloud.ir/bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./init.sh:/init.sh
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
    # command: ["sh", "/init.sh"]
  datanode:
    image: docker.arvancloud.ir/bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
      - ./init.sh:/init.sh
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    command: ["sh", "/init.sh"]
